defaults:
  - train_transform: simple
  - test_transform: simple

name: dreambooth1
num_classes: 37
batch_size: 64
num_workers: 15
real_images_val_path: ${data_dir}/val
test_path: ${data_dir}/test
train_path: ${data_dir}/train/dreambooth2
